using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

namespace StealthGame
{
    public class PlayerMovement : MonoBehaviour
    {
        private List<string> m_OwnedKeys = new List<string>();
        public InputAction MoveAction;
        
        public float walkSpeed = 1.0f;
        public float turnSpeed = 20f;
        AudioSource m_AudioSource;
        Rigidbody m_Rigidbody;
        Vector3 m_Movement;
        Quaternion m_Rotation = Quaternion.identity;
        Animator m_Animator;

        void Start ()
        {
            m_Rigidbody = GetComponent<Rigidbody> ();
            MoveAction.Enable();
            m_Animator = GetComponent<Animator>();
            m_AudioSource = GetComponent<AudioSource>();
        }

        void FixedUpdate ()
        {
            var pos = MoveAction.ReadValue<Vector2>();
            
            float horizontal = pos.x;
            float vertical = pos.y;
            
            m_Movement.Set(horizontal, 0f, vertical);
            m_Movement.Normalize ();

            bool hasHorizontalInput = !Mathf.Approximately (horizontal, 0f);
            bool hasVerticalInput = !Mathf.Approximately (vertical, 0f);
            bool isWalking = hasHorizontalInput || hasVerticalInput;
            m_Animator.SetBool ("IsWalking", isWalking);

            Vector3 desiredForward = Vector3.RotateTowards (transform.forward, m_Movement, turnSpeed * Time.deltaTime, 0f);
            m_Rotation = Quaternion.LookRotation (desiredForward);
            
            m_Rigidbody.MoveRotation (m_Rotation);
            m_Rigidbody.MovePosition (m_Rigidbody.position + m_Movement * walkSpeed * Time.deltaTime);
        
            
            if (isWalking)
            {
                if (!m_AudioSource.isPlaying)
                {
                    m_AudioSource.Play();
                }
            }
            else
            {
                m_AudioSource.Stop();
            }
        }

        public void AddKey(string keyName)
        {
            m_OwnedKeys.Add(keyName);
        }

        public bool OwnKey(string keyName)
        {
            return m_OwnedKeys.Contains(keyName);
        }
    }
}